"""
api.py
======

FastAPI backend for the System Health Monitor project.

This module exposes the data collected by config.py (in-memory monitoring
state) and database.py (persisted SQLite history) over a REST API, so a
frontend dashboard or other client can query system health information.

Run with:
    uvicorn api:app --reload

Author: System Health Monitor Project
"""

import logging
from datetime import datetime
from typing import List, Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, ConfigDict

import config
import database

# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("api")


# ---------------------------------------------------------------------------
# FastAPI app initialization
# ---------------------------------------------------------------------------
app = FastAPI(
    title="System Health Monitor API",
    description="API Backend for AI-Based System Health Monitoring Platform",
    version="1.0",
)


# ---------------------------------------------------------------------------
# Pydantic response models
# ---------------------------------------------------------------------------
class RootResponse(BaseModel):
    """Response model for the root health-check endpoint."""
    message: str


class StatusResponse(BaseModel):
    """Response model for /status - current monitoring state."""
    monitoring_active: bool
    alert_count: int


class SystemMetricResponse(BaseModel):
    """Response model for a single system_metrics row."""
    model_config = ConfigDict(from_attributes=True)

    id: int
    timestamp: datetime
    cpu_usage: float
    ram_usage: float
    disk_usage: float
    network_sent: float
    network_received: float
    system_uptime: float
    running_processes: int


class SystemProcessResponse(BaseModel):
    """Response model for a single system_processes row."""
    model_config = ConfigDict(from_attributes=True)

    id: int
    timestamp: datetime
    process_name: str
    pid: Optional[int] = None
    cpu_usage: float
    ram_usage: float


class AlertResponse(BaseModel):
    """Response model for a single alert generated by config.py's alert engine."""
    timestamp: str
    type: str
    value: float
    threshold: float


class TestRunResponse(BaseModel):
    """Response model for a single test_run row (a historical monitoring session)."""
    model_config = ConfigDict(from_attributes=True)

    id: int
    start_time: datetime
    end_time: Optional[datetime] = None
    total_alerts: int


class ReportResponse(BaseModel):
    """
    Response model for /report - a summary of the most recent monitoring
    session, derived from config.py's in-memory data (mirrors the fields
    written to system_report.csv by generate_summary_report()).
    """
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    total_runtime_seconds: float
    average_cpu_usage: float
    peak_cpu_usage: float
    average_ram_usage: float
    peak_ram_usage: float
    total_alerts_generated: int
    total_samples_collected: int


class ErrorResponse(BaseModel):
    """Generic error response model."""
    detail: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@app.get("/", response_model=RootResponse, tags=["Health"])
def read_root() -> RootResponse:
    """
    Root endpoint. Confirms the API is running.

    Returns:
        RootResponse: A simple confirmation message.
    """
    return RootResponse(message="System Health Monitor API Running")


@app.get("/status", response_model=StatusResponse, tags=["Monitoring"])
def get_status() -> StatusResponse:
    """
    Return the current monitoring status, sourced from config.py's
    in-memory shared state.

    Returns:
        StatusResponse: Current monitoring_active flag and alert_count.

    Raises:
        HTTPException: 500 if the status cannot be read.
    """
    try:
        return StatusResponse(
            monitoring_active=config.monitoring_active,
            alert_count=config.alert_count,
        )
    except Exception as exc:
        logger.error("Failed to fetch status: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to retrieve monitoring status.")


@app.get("/metrics", response_model=List[SystemMetricResponse], tags=["Monitoring"])
def get_metrics(limit: int = 10) -> List[SystemMetricResponse]:
    """
    Return the most recent system metrics from the database.

    Args:
        limit (int): Maximum number of records to return. Defaults to 10.

    Returns:
        List[SystemMetricResponse]: Most recent metric snapshots, newest first.

    Raises:
        HTTPException: 500 if the database query fails.
    """
    try:
        metrics = database.get_latest_metrics(limit=limit)
        return [SystemMetricResponse.model_validate(m) for m in metrics]
    except Exception as exc:
        logger.error("Failed to fetch metrics: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to retrieve system metrics.")


@app.get("/processes", response_model=List[SystemProcessResponse], tags=["Monitoring"])
def get_processes(limit: int = 10) -> List[SystemProcessResponse]:
    """
    Return the most recent top-process records from the database.

    Args:
        limit (int): Maximum number of records to return. Defaults to 10.

    Returns:
        List[SystemProcessResponse]: Most recent process snapshots, newest first.

    Raises:
        HTTPException: 500 if the database query fails.
    """
    try:
        processes = database.get_latest_processes(limit=limit)
        return [SystemProcessResponse.model_validate(p) for p in processes]
    except Exception as exc:
        logger.error("Failed to fetch processes: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to retrieve process records.")


@app.get("/alerts", response_model=List[AlertResponse], tags=["Monitoring"])
def get_alerts() -> List[AlertResponse]:
    """
    Return all alerts generated during the current monitoring session,
    sourced directly from config.py's in-memory `alerts_generated` list.

    Returns:
        List[AlertResponse]: All alerts generated so far.

    Raises:
        HTTPException: 500 if alerts cannot be read.
    """
    try:
        return [AlertResponse(**alert) for alert in config.alerts_generated]
    except Exception as exc:
        logger.error("Failed to fetch alerts: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to retrieve alerts.")


@app.get("/report", response_model=ReportResponse, tags=["Reporting"])
def get_report() -> ReportResponse:
    """
    Return a summary report of the current/most recent monitoring session,
    computed live from config.py's in-memory metrics data (the same data
    generate_summary_report() in config.py writes to system_report.csv).

    Returns:
        ReportResponse: Summary statistics for the current session.

    Raises:
        HTTPException: 500 if the report cannot be computed.
    """
    try:
        metrics_data = config.system_metrics_data

        if metrics_data:
            cpu_values = [m.get("cpu_usage_percent", 0.0) for m in metrics_data]
            ram_values = [m.get("ram_usage_percent", 0.0) for m in metrics_data]
            avg_cpu = sum(cpu_values) / len(cpu_values)
            peak_cpu = max(cpu_values)
            avg_ram = sum(ram_values) / len(ram_values)
            peak_ram = max(ram_values)
        else:
            avg_cpu = peak_cpu = avg_ram = peak_ram = 0.0

        start_time_str = config.start_time.isoformat() if config.start_time else None
        end_time_str = config.end_time.isoformat() if config.end_time else None

        if config.start_time:
            reference_end = config.end_time or datetime.now()
            total_runtime_seconds = (reference_end - config.start_time).total_seconds()
        else:
            total_runtime_seconds = 0.0

        return ReportResponse(
            start_time=start_time_str,
            end_time=end_time_str,
            total_runtime_seconds=round(total_runtime_seconds, 2),
            average_cpu_usage=round(avg_cpu, 2),
            peak_cpu_usage=round(peak_cpu, 2),
            average_ram_usage=round(avg_ram, 2),
            peak_ram_usage=round(peak_ram, 2),
            total_alerts_generated=config.alert_count,
            total_samples_collected=len(metrics_data),
        )
    except Exception as exc:
        logger.error("Failed to generate report: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to generate report.")


@app.get("/test-runs", response_model=List[TestRunResponse], tags=["Reporting"])
def get_test_runs(limit: int = 20) -> List[TestRunResponse]:
    """
    Return all historical monitoring runs from the database.

    Args:
        limit (int): Maximum number of records to return. Defaults to 20.

    Returns:
        List[TestRunResponse]: Historical test_run records, newest first.

    Raises:
        HTTPException: 500 if the database query fails.
    """
    try:
        runs = database.get_test_runs(limit=limit)
        return [TestRunResponse.model_validate(r) for r in runs]
    except Exception as exc:
        logger.error("Failed to fetch test runs: %s", exc)
        raise HTTPException(status_code=500, detail="Failed to retrieve test runs.")


# ---------------------------------------------------------------------------
# Startup event - ensure database tables exist before serving requests
# ---------------------------------------------------------------------------
@app.on_event("startup")
def on_startup() -> None:
    """
    Ensure the database is initialized (tables created) when the API starts.
    """
    try:
        database.initialize_database()
        logger.info("API startup complete. Database initialized.")
    except Exception as exc:
        logger.error("Database initialization failed on startup: %s", exc)


# ---------------------------------------------------------------------------
# Standalone run support (in addition to `uvicorn api:app --reload`)
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import uvicorn
    logger.info("Starting System Health Monitor API via uvicorn...")
    uvicorn.run("api:app", host="127.0.0.1", port=8000, reload=True)